### ISSUE TITLE
Missing finally

### ISSUE THREAD

**Issue by JaceHensley** [xf00f/web3x#18]
It seems like `finally` is missing from the `PromiEvent` class. I'm getting this error when trying to pull in this library to a react app that was created with CRA

```
Property 'then' in type 'PromiEvent<T>' is not assignable to the same property in base type 'Promise<T>'.
  Type '<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null | undefined) => PromiEvent<...>' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null | undefined) => Promise<...>'.
    Property 'finally' is missing in type 'PromiEvent<TResult1 | TResult2>' but required in type 'Promise<TResult1 | TResult2>'.

15     then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null | undefined): PromiEvent<TResult1 | TResult2>;
       ~~~~

  node_modules/typescript/lib/lib.es2018.promise.d.ts:31:5
    31     finally(onfinally?: (() => void) | undefined | null): Promise<T>
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'finally' is declared here.
```

I think it makes since to add here, I can do this in a PR if you want

**Comment by JaceHensley** [comment]
So I changed my tsconfig.json to not use `esnext` in lib, but when doing `yarn install` it still complained with the message above. I ended up having to keep the change to tsconfig and then use `npm install` instead. I'm installing this package through another package that is a git package so I don't know if yarn just handles git packages oddly or not. 🤷‍♂️

This is no longer a blocker for me, but it may cause other people pain

**Comment by xf00f** [comment]
@JaceHensley I've release v2.0.4 which adds finally support to the PromiEvent.
The issue is that depending on whether or not the client code supports Promises with finally, web3x needs to adapt accordingly. This isn't possible at compile time without forcing the user to use a specific Promise implementation. I've basically hacked it to detect at runtime if finally is *not* supported and to throw an error.

As a side note, I'll soon be releasing the 3.0 branch. This does away with PromiEvents completely as it is not a pleasant approach exactly because of issues like this.

**Comment by JaceHensley** [comment]
Thanks for the quick response + fix!
