### ISSUE TITLE
Cannot `call()`.

### ISSUE THREAD

**Issue by hickscorp** [xf00f/web3x#53]
I think there is an issue with the way Web3x decodes return values.

From a solidity (ERC20 compliant) token, we have a `totalSupply` method that returns an `uint256`.
From our code, we go:

```
token.methods.totalSupply().call()
```
where `token` is a `new Token(eth, TOKEN_ADDRESS)` generated using `web3x-codegen`.

The result looks like this:

```
index.js:155 Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas?
    at ABICoder.decodeParameters (index.js:155)
    at ContractFunctionEntry.decodeReturnValue (contract-function-entry.js:67)
    at Tx._callee2$ (tx.js:106)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:282)
    at Generator.prototype.<computed> [as next] (runtime.js:116)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

It is worth mentioning that the generated typescript code for `Token.ts` looks like this:

```
interface TokenMethods {
    totalSupply(): TxCall<string>;
    ...
}
```

Shouldn't this be a `BigNumber` or something like that?

**Comment by hickscorp** [comment]
This problem was fixed on its own - I believe because we weren't connected to the correct network ID so the call was ending in an incorrect address.

**Comment by xf00f** [comment]
@hickscorp Thanks! I was just investigating, but couldn't reproduce. You are right in suggesting it should probably return a BN rather than a string. This library was ported from `web3.js` and that is what `web3.js` does. There maybe a good reason why this comes back as a string rather than a BN, I think I investigated it once before so perhaps it's a non trivial issue.

It would be a breaking change regardless so perhaps I'll sort in v5.
