### ISSUE TITLE
BN typescript error

### ISSUE THREAD

**Issue by xpepermint** [xf00f/web3x#6]
I'm testing this module and here's the error I see when I try to compile the code.
```
error TS2497: Module '"../node_modules/@types/bn.js/index"' resolves to a non-module entity and cannot be imported using this construct.

1 import * as BN from 'bn.js';
```

**Comment by xf00f** [comment]
Can you check the example projects at https://github.com/xf00f/web3x/tree/master/example-projects and confirm you have the right settings for your environment. It's possible you require additional `tsconfig.json` settings for example.
Otherwise if you can post a minimal repository to reproduce I'll take a look.

**Comment by xpepermint** [comment]
I see. Thx.
